# Generated by Django 5.0.1 on 2024-02-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
